<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNx0qOwV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNx0qOwV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNx0qOwV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNx0qOwV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNx0qOwV\App_KernelDevDebugContainer([
    'container.build_hash' => 'Nx0qOwV',
    'container.build_id' => 'b0de37d2',
    'container.build_time' => 1665302346,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNx0qOwV');
